blank_issues_enabled: false
contact_links:
  - name: 💬 Kometa Discord Support
    url: https://discord.gg/kometa-822460010649878528
    about: For support questions, setup help, and quick troubleshooting, please ask in Discord first.
