name: Docker Develop Build

on:
  workflow_run:
    workflows: [ "Master Release" ]
    types: [ completed ]

jobs:

  docker-build-develop:
    name: Docker
    uses: ./.github/workflows/docker-build.yml
    secrets: inherit
    with:
      branch: develop
      branch_name: develop
      tag_name: develop

