name: Docker Version Build

on:
  create:
    tags: [ v* ]

jobs:

  get-version:
    if: ${{ startsWith(github.ref, 'refs/tags/v0') || startsWith(github.ref, 'refs/tags/v1') || startsWith(github.ref, 'refs/tags/v2') }}
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}
    steps:

      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT


  docker-build-version:
    name: Docker
    uses: ./.github/workflows/docker-build.yml
    secrets: inherit
    needs: [ get-version ]
    with:
      tag_name: ${{ needs.get-version.outputs.version }}


  make-releases:
    name: Make Releases
    runs-on: ubuntu-latest
    needs: [ get-version ]
    steps:

      - name: Create App Token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_TOKEN }}

      - name: Check Out Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: develop

      - name: Build Changelog
        id: build-changelog
        run: |
          latest_tag="$(git describe --tags --abbrev=0 ${{ needs.get-version.outputs.version }}^)"
          echo "${latest_tag}"
          
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "changelog<<$EOF" >> $GITHUB_OUTPUT
          echo "## Commits" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          GIT_LOG_OUTPUT=$(git log ${latest_tag}..${{ needs.get-version.outputs.version }} --pretty='* [`%h`](https://github.com/Kometa-Team/Quickstart/commit/%H): %s (@%an)')
          echo "$GIT_LOG_OUTPUT" | base64 -w 0 >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo "[**Full Code Changelog**](https://github.com/Kometa-Team/Quickstart/compare/${latest_tag}...${{ needs.get-version.outputs.version }})" >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT

      - name: Create Releases
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          CHANGELOG_DECODED=$(echo "${{ steps.build-changelog.outputs.changelog }}" | base64 -d)
          echo "$CHANGELOG_DECODED"
          
          if gh release view prerelease > /dev/null 2>&1; then
            gh release delete prerelease --cleanup-tag
            sleep 60
          fi
          
          gh release create prerelease --prerelease \
            --title "${{ vars.NAME }} ${{ github.event.ref }} Develop Build 0" \
            --notes "No current changes from the Master branch. Using this version will trigger updates based on the Develop branch." \
            --target "${{ needs.increment-build.outputs.commit-hash }}"
          
          gh release create ${{ github.event.ref }} \
            --title "${{ vars.NAME }} ${{ github.event.ref }}" \
            --notes "$CHANGELOG_DECODED" \
            --target "${{ needs.increment-build.outputs.commit-hash }}"

