name: Docker Latest Build

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:

  docker-build-latest:
    name: Docker
    uses: ./.github/workflows/docker-build.yml
    secrets: inherit
    with:
      tag_name: latest

