name: Increment Build

on:
  pull_request_target:
    branches: [ develop ]
    types: [ closed ]

jobs:

  verify-changes:
    name: Verify Changes
    runs-on: ubuntu-latest
    if: github.base_ref == 'develop' && github.event.pull_request.merged
    outputs:
      build: ${{ steps.list-changes.outputs.build }}
    steps:

      - name: Display Refs
        run: |
          echo "Base Repo: ${{ github.event.pull_request.base.repo.full_name }}"
          echo "Base Ref: ${{ github.base_ref }}"
          echo "Head Repo: ${{ github.event.pull_request.head.repo.full_name }}"
          echo "Head Ref: ${{ github.event.pull_request.head.ref }}"

      - name: Check Out Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: develop

      - name: Get changes
        id: get-changes
        run: echo "files=$(git diff --name-only HEAD^ | xargs)" >> $GITHUB_OUTPUT

      - name: List changed files
        id: list-changes
        run: |
          for file in ${{ steps.get-changes.outputs.files }}; do
              if [[ $file =~ ^(modules|static|templates|quickstart.py|requirements.txt|.dockerignore|Dockerfile).*$ ]] ; then
                  echo "$file will trigger docker build"
                  echo "build=true" >> $GITHUB_OUTPUT
              else
                  echo "$file will not trigger docker build"
              fi
          done


  increment-build:
    name: Increment Build
    runs-on: ubuntu-latest
    needs: [ verify-changes ]
    if: needs.verify-changes.outputs.build == 'true'
    outputs:
      version: ${{ steps.update-version.outputs.version }}
      build-value: ${{ steps.update-version.outputs.build-value }}
      commit-msg: ${{ steps.update-version.outputs.commit-msg }}
      commit-hash: ${{ steps.update-version.outputs.commit-hash }}
      commit-short: ${{ steps.update-version.outputs.commit-short }}
      pr-tag: ${{ steps.update-version.outputs.pr-tag }}
    steps:

      - name: Create App Token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_TOKEN }}

      - name: Check Out Repo
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: develop
          fetch-depth: 0

      - name: Update VERSION File
        id: update-version
        run: |
          branch_name=${{ github.event.pull_request.head.ref }}
          repo_name=${{ github.event.pull_request.head.repo.full_name }}
          base_name="${repo_name%/*}"
          if [[ "${branch_name}" =~ ^(master|develop)$ ]]; then
              pr_tag="${base_name}"
          else
              pr_tag="${branch_name}"
          fi
          echo "pr-tag=${pr_tag}" >> $GITHUB_OUTPUT

          version=$(cat VERSION)
          build_value=$(cat BUILDNUM)
          next_build_value="$((${build_value} + 1))"
          part_value=$(cat PART)
        
          old_msg=$(git log -1 HEAD --pretty=format:%s)
          new_msg="[${next_build_value}] ${old_msg}"

          echo "version=${version}" >> $GITHUB_OUTPUT
          echo "build-value=${next_build_value}" >> $GITHUB_OUTPUT
          echo "commit-msg=${old_msg}" >> $GITHUB_OUTPUT
          echo "commit-short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

          echo "$next_build_value" > "BUILDNUM"
          echo "" > "PART"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add BUILDNUM
          git add PART
          git commit -m "${new_msg}" --amend
          git push origin develop --force-with-lease

          echo "commit-hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT


  docker-build-develop:
    name: Docker ${{ matrix.tag }} Build
    runs-on: ubuntu-latest
    needs: [ increment-build ]
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'linux/amd64'
            dockerfile: 'Dockerfile'
            tag: 'amd64'
          - platform: 'linux/arm64'
            dockerfile: 'Dockerfile'
            tag: 'arm64'
          - platform: 'linux/arm/v7'
            dockerfile: 'Dockerfile.arm7'
            tag: 'armv7'
    steps:

      - name: Create App Token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_TOKEN }}

      - name: Check Out Repo
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: develop

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: ./
          file: ./${{ matrix.dockerfile }}
          build-args: |
            "BRANCH_NAME=develop"
          platforms: ${{ matrix.platform }}
          tags: ${{ vars.DOCKER_TEAM }}/${{ vars.DOCKER_REPO }}:develop-${{ matrix.tag }}
          push: true
          provenance: false
          sbom: false


  create-manifest:
    name: Create Docker Manifest
    runs-on: ubuntu-latest
    needs: [ docker-build-develop ]
    steps:

      - name: Create App Token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_TOKEN }}

      - name: Check Out Repo
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: develop

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Create and Push Manifest
        run: |
          docker manifest create \
            ${{ vars.DOCKER_TEAM }}/${{ vars.DOCKER_REPO }}:develop \
            --amend ${{ vars.DOCKER_TEAM }}/${{ vars.DOCKER_REPO }}:develop-amd64 \
            --amend ${{ vars.DOCKER_TEAM }}/${{ vars.DOCKER_REPO }}:develop-arm64 \
            --amend ${{ vars.DOCKER_TEAM }}/${{ vars.DOCKER_REPO }}:develop-armv7
          docker manifest push ${{ vars.DOCKER_TEAM }}/${{ vars.DOCKER_REPO }}:develop

      - name: Remove Extra Images
        run: |
          HUB_TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d "{\"username\": \"${{ secrets.DOCKER_HUB_USERNAME }}\", \"password\": \"${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}\"}" https://hub.docker.com/v2/users/login/ | jq -r .token)
          
          curl -i -X DELETE -H "Accept: application/json" -H "Authorization: JWT $HUB_TOKEN" \
          https://hub.docker.com/v2/repositories/${{ vars.DOCKER_TEAM }}/${{ vars.DOCKER_REPO }}/tags/develop-amd64/
          
          curl -i -X DELETE -H "Accept: application/json" -H "Authorization: JWT $HUB_TOKEN" \
          https://hub.docker.com/v2/repositories/${{ vars.DOCKER_TEAM }}/${{ vars.DOCKER_REPO }}/tags/develop-arm64/
          
          curl -i -X DELETE -H "Accept: application/json" -H "Authorization: JWT $HUB_TOKEN" \
          https://hub.docker.com/v2/repositories/${{ vars.DOCKER_TEAM }}/${{ vars.DOCKER_REPO }}/tags/develop-armv7/


  create-pre-release:
    name: Create Pre-Release
    runs-on: ubuntu-latest
    needs: [ increment-build, create-manifest ]
    steps:

      - name: Create App Token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_TOKEN }}

      - name: Check Out Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: develop

      - name: Build Changelog
        id: build-changelog
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "changelog<<$EOF" >> $GITHUB_OUTPUT
          echo "## Commits" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo "$(git log $(git describe --tags --abbrev=0 prerelease^)..HEAD --pretty='* [`%h`](https://github.com/Kometa-Team/Quickstart/commit/%H): %s (@%an)' --reverse)" >> $GITHUB_OUTPUT
          echo "" >> $GITHUB_OUTPUT
          echo "[**Full Code Changelog**](https://github.com/Kometa-Team/Quickstart/compare/$(git describe --tags --abbrev=0 prerelease^)...prerelease)" >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT

      - name: Show Changelog
        id: show-changelog
        run: echo "${{ steps.build-changelog.outputs.changelog }}"

      - name: Remove Old Pre-Release
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          if gh release view prerelease > /dev/null 2>&1; then
            gh release delete prerelease --cleanup-tag
          fi

      - name: Create Pre-Release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ vars.NAME }} ${{ needs.increment-build.outputs.version }} Build ${{ needs.increment-build.outputs.build-value }}
          commit: ${{ needs.increment-build.outputs.commit-hash }}
          body: ${{ steps.build-changelog.outputs.changelog }}
          prerelease: true
          tag: prerelease
          token: ${{ steps.app-token.outputs.token }}


  build-notification:
    name: Build Notification
    runs-on: ubuntu-latest
    needs: [ create-pre-release ]
    steps:

      - name: Discord Success Notification
        uses: Kometa-Team/discord-notifications@master
        if: success()
        with:
          webhook_id_token: ${{ secrets.BUILD_WEBHOOK }}
          title: "${{ vars.NAME }} develop: ${{ vars.TEXT_SUCCESS }}"
          url: https://github.com/Kometa-Team/${{ vars.REPO_NAME }}/actions/runs/${{ github.run_id }}
          color: ${{ vars.COLOR_SUCCESS }}
          username: ${{ vars.BOT_NAME }}
          avatar_url: ${{ vars.BOT_IMAGE }}
          author: ${{ vars.DOCKER_NAME }}
          author_icon_url: ${{ vars.DOCKER_IMAGE }}

      - name: Discord Failure Notification
        uses: Kometa-Team/discord-notifications@master
        if: failure()
        with:
          webhook_id_token: ${{ secrets.BUILD_WEBHOOK }}
          message: ${{ vars.BUILD_FAILURE_ROLE }}
          title: "${{ vars.NAME }} develop: ${{ vars.TEXT_FAILURE }}"
          url: https://github.com/Kometa-Team/${{ vars.REPO_NAME }}/actions/runs/${{ github.run_id }}
          color: ${{ vars.COLOR_FAILURE }}
          username: ${{ vars.BOT_NAME }}
          avatar_url: ${{ vars.BOT_IMAGE }}
          author: ${{ vars.DOCKER_NAME }}
          author_icon_url: ${{ vars.DOCKER_IMAGE }}