name: Tag New Version

on:
  push:
    branches: [ master ]

jobs:

  tag:
    name: Tag New Version
    runs-on: ubuntu-latest
    steps:

      - name: Create App Token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_TOKEN }}

      - name: Check Out Repo
        uses: actions/checkout@v6
        with:
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: 2

      - name: Create Tag From VERSION File
        uses: Kometa-Team/tag-new-version@master
        with:
          version-command: |
            cat VERSION